jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - checkout
      - run: ruby --version
    steps:
        - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: RubyCircleTest-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: RubyCircleTest-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Setup the environment
      - run: cp .sample.env .env
      # Setup the database
      - run: bundle exec rake db:setup
      # Run the tests
      - run: bundle exec rake
